### ISSUE TITLE
telegram.error.Conflict

### ISSUE THREAD

**Issue by JuneBridge03** [Pikachu-skku/PIKACHU-SERVER#2]
**Error Message**

telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running      
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\ext\updater.py", line 651, in _network_loop_retry
    if not action_cb():
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\ext\updater.py", line 606, in polling_action_cb
    allowed_updates=allowed_updates,
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\ext\extbot.py", line 232, in get_updates   
    api_kwargs=api_kwargs,
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 3061, in get_updates
    api_kwargs=api_kwargs,
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 299, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 366, in post       
    **urlopen_kwargs,
  File "C:\Users\potat\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

- we have to fix it

**Comment by JuneBridge03** [comment]
Finished
